openapi: 3.1.0

info:
  title: Matrix API
  version: 0.1.0

paths:
  /items:
    get:
      tags:
        - items
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: part.type
          schema:
            $ref: "#/components/schemas/PartType"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ItemResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - items
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemRequest"
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ItemResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /parts:
    get:
      tags:
        - parts
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: type
          schema:
            $ref: "#/components/schemas/PartType"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PartResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users:
    post:
      tags:
        - users
      security:
        - OAuth2: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /users/{userId}:
    get:
      tags:
        - users
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  securitySchemes:
    OAuth2:
      type: apiKey
      in: header
      name: Authorization

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
    Conflict:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
    InternalServerError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
    Unauthorized:
      description: Unauthorized

  schemas:
    Problem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
      required:
        - type
        - title
        - status
        - detail

    Price:
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
      required:
        - amount
        - currency

    Condition:
      type: string
      enum:
        - New
        - Used
        - Refurbished
        - ForParts

    UserResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        name:
          type: string
      required:
        - id
        - createdAt
        - updatedAt
        - name

    UserRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        address:
          type: object
          properties:
            line1:
              type: string
            line2:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            country:
              type: string
          required:
            - line1
            - city
            - state
            - postalCode
            - country
      required:
        - email
        - phoneNumber
        - firstName
        - lastName
        - dateOfBirth
        - address

    PartType:
      type: string
      enum:
        - CentralProcessingUnit
        - CentralProcessingUnitCooler
        - GraphicsProcessingUnit
        - Storage

    PartResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        type:
          $ref: "#/components/schemas/PartType"
        name:
          type: string
        attributes:
          type: object
          additionalProperties: true
      required:
        - id
        - createdAt
        - updatedAt
        - type
        - name
        - attributes

    ItemResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        user:
          $ref: "#/components/schemas/UserResponse"
        part:
          $ref: "#/components/schemas/PartResponse"
        defaultPrice:
          $ref: "#/components/schemas/ItemPriceResponse"
        condition:
          $ref: "#/components/schemas/Condition"
        description:
          type: string
      required:
        - id
        - createdAt
        - updatedAt
        - user
        - part
        - defaultPrice
        - condition

    ItemRequest:
      type: object
      properties:
        partId:
          type: string
        defaultPrice:
          type: number
        condition:
          $ref: "#/components/schemas/Condition"
        description:
          type: string
      required:
        - partId
        - defaultPrice
        - condition

    ItemPriceResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        value:
          type: number
        currency:
          type: string
      required:
        - id
        - createdAt
        - updatedAt
        - value
        - currency
